// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddressBook.proto

package serialization.protobuf;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  java.util.List<serialization.protobuf.Person>
      getPersonList();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  serialization.protobuf.Person getPerson(int index);
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  java.util.List<? extends serialization.protobuf.PersonOrBuilder>
      getPersonOrBuilderList();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  serialization.protobuf.PersonOrBuilder getPersonOrBuilder(
      int index);
}
